---
- include: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Install kubernetes
  action: "{{ ansible_pkg_mgr }}"
  args:
        name: kubernetes
        state: latest
  notify:
        - restart daemons
  when: not is_atomic

- name: write the global config file
  template: src=config.j2 dest=/etc/kubernetes/config
  notify:
          - restart daemons
